menu:
- {name: 'Publications', url: '/publications'}
# - {name: 'Conferences', url: '/conferences'}
- {name: 'Projects', url: '/projects'}
- {name: 'Curriculum Vitae', url: '/cv'}
- {name: 'Posts', url: '/posts'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/MunQ-Lee'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=AKOUtfoAAAAJ'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0001-6643-8580'}
- {icon: 'instagram', link: 'https://www.instagram.com/munkyu94'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/munq-lee'}

contacts:
- {name: 'Munkyu Lee', title: 'Ph.D. candidate', department: 'Intelligent Semiconductor Engineering', major: 'System Software', institution: 'Chung-Ang University', institution_address: '84, Heukseok-ro, Dongjak-gu, Seoul, Republic of Korea', phone: '+82 10-7199-9765', email: 'dse112@cau.ac.kr', office: '209-309', image: 'assets/img/contact.jpg'}
